### ISSUE TITLE
async channel does not compile for me.

### ISSUE THREAD

**Issue by ruststarter** [smol-rs/async-channel#94] opened 2024-05-15 10:05 UTC
I have a rust program using gtk4. My cargo file is the following:

[package]
name = "mycode"
version = "0.1.0"
edition = "2024"
[dependencies]
async-channel = "2.3.0"
gtk4 = { version = "0.8.1", features = ["v4_6"] }
pollster = "0.3.0"
reqwest = { version = "0.12.2", features = ["blocking"] }
rfd = "0.14.1"
serde = "1.0.197"
serde_json = "1.0.115"
yup-oauth2 = "8.3.3"

And I get the following error. 

cargo build
   Compiling async-channel v2.3.0
error[E0432]: unresolved import `concurrent_queue::ForcePushError`
  --> /home/vania/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-channel-2.3.0/src/lib.rs:50:41
   |
50 | ...rentQueue, ForcePushError, PopError, PushError};
   |               ^^^^^^^^^^^^^^ no `ForcePushError` in the root

error[E0599]: no method named `force_push` found for struct `ConcurrentQueue` in the current scope
   --> /home/vania/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-channel-2.3.0/src/lib.rs:313:34
    |
313 |         match self.channel.queue.force_push(msg) {
    |                                  ^^^^^^^^^^ method not found in `ConcurrentQueue<T>`

Is it a version problem ??

**Comment by taiki-e** [comment] 2024-05-15 10:06
Duplicate of #92

**Closed by taiki-e** 2024-05-15 10:06 UTC
